version: '2.0'

services:
  restservices:
    image: docker.mdl.cloud/masud_hasan/spring-petclinic-rest:latest
    ports:
    - "9966:9966"
 
    environment: 
      - SERVICE_9966_NAME=spring-petclinic
      - SERVICE_TAGS=public   
    network_mode: "bridge"
  
